apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-ha-local
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: patroni-postgres-ha
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-ha
  source:
    repoURL: git@github.com:eleeyeah/patroni-postgres-ha.git
    targetRevision: HEAD
    path: helm-charts/postgres-ha
    helm:
      releaseName: postgres-ha
      valueFiles:
        - values.yaml
        - values-local.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  # Requires postgres-operator (sync-wave 0) and a working StorageClass
